all:
	python3 repo_to_text.py --cfg /Users/ryh/Documents/ORNL/code/imsrg_corpus/corpus/config.yaml --repo_path ../src -w 450000 -o ./

env:
	python3 -m venv ./venv; source venv/bin/activate; python3 -m pip install nltk pyyaml
